In [3]:
import hydrobr
import pandas as pd

In [4]:
list_station = hydrobr.get_data.ANA.list_prec_stations()
df_stations = pd.DataFrame(list_station)
df_stations

DeprecationWarning: The method name have changed. Use list_prec() instead of list_prec_stations()

In [ ]:
mask = (df_stations["Responsible"].astype(str).str.upper() == "INMET") & (df_stations["City"].astype(str).str.upper() == "SÃO PAULO")

df_stations[mask]

,Name,Code,Type,SubBasin,City,State,Responsible,Latitude,Longitude,StartDate,EndDate,NYD,MD,N_YWOMD,YWMD
9293,SÃO PAULO (HORTO CANTAR.),02346114,2,62,SÃO PAULO,SÃO PAULO,INMET,-23.4500,-46.6500,1961/01/01,1982/07/31,22,20.7,14,36.4
9294,SÃO PAULO (FAC. HIGIENE),02346115,2,62,SÃO PAULO,SÃO PAULO,INMET,-23.5667,-46.6333,1961/01/01,1965/05/31,5,0.0,4,20.0
9296,SÃO PAULO (MIRANTE SANTANA),02346117,2,62,SÃO PAULO,SÃO PAULO,INMET,-23.5000,-46.6167,1961/01/01,2019/06/30,59,0.0,58,1.7
9297,SÃO PAULO (SANTO AMARO),02346120,2,62,SÃO PAULO,SÃO PAULO,INMET,-23.5500,-46.6333,1961/01/01,1965/04/30,5,15.3,1,80.0

In [ ]:

list_station_city = df_stations[df_stations.City=="SÃO PAULO"]
list_station_city

,Name,Code,Type,SubBasin,City,State,Responsible,Latitude,Longitude,StartDate,EndDate,NYD,MD,N_YWOMD,YWMD
9217,PERUS,02346027,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4000,-46.7500,1936/10/09,1997/09/25,62,11.6,32,48.4
9221,CANTAREIRA (SABESP),02346031,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4500,-46.6167,1940/10/01,1969/12/30,30,3.9,21,30.0
9222,HORTO FLORESTAL,02346032,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4667,-46.6333,1899/01/01,2003/10/09,105,33.8,56,46.7
9224,BARROCADA,02346034,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4167,-46.5667,1940/11/01,1998/06/30,59,0.2,52,11.9
9225,ENGORDADOR,02346035,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4000,-46.5833,1940/10/01,1997/07/31,58,0.8,48,17.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9495,VILA CARRÃO,02346397,2,62,SÃO PAULO,SÃO PAULO,ANA,-23.5500,-46.5167,1981/06/13,1991/02/22,11,0.5,8,27.3
9496,PIRAJUCARA,02346398,2,62,SÃO PAULO,SÃO PAULO,ANA,-23.6500,-46.7833,1981/06/16,1990/12/05,10,4.0,2,80.0
9506,ETD - PINHEIROS,02346412,2,62,SÃO PAULO,SÃO PAULO,EMAE,-23.5833,-46.7167,1985/09/06,1986/06/30,2,0.3,0,100.0
9507,ETD - GUMERCINDO,02346413,2,62,SÃO PAULO,SÃO PAULO,EMAE,-23.6167,-46.6167,1983/10/01,1986/06/30,4,0.8,1,75.0
9511,GUARAU,02346418,2,62,SÃO PAULO,SÃO PAULO,DAEE-SP,-23.4333,-46.6500,1985/01/01,2018/05/31,34,1.4,22,35.3

In [ ]:
inmet_station = df_stations[df_stations.Responsible=="INMET"]

In [ ]:
code_station = list_station_city.Code.to_list()
code_station

['02346027',
 '02346031',
 '02346032',
 '02346034',
 '02346035',
 '02346036',
 '02346041',
 '02346042',
 '02346044',
 '02346045',
 '02346046',
 '02346047',
 '02346050',
 '02346054',
 '02346057',
 '02346059',
 '02346092',
 '02346100',
 '02346108',
 '02346110',
 '02346114',
 '02346115',
 '02346117',
 '02346120',
 '02346152',
 '02346153',
 '02346154',
 '02346157',
 '02346158',
 '02346161',
 '02346163',
 '02346164',
 '02346165',
 '02346179',
 '02346180',
 '02346181',
 '02346183',
 '02346186',
 '02346191',
 '02346192',
 '02346197',
 '02346199',
 '02346201',
 '02346203',
 '02346204',
 '02346207',
 '02346217',
 '02346222',
 '02346231',
 '02346233',
 '02346236',
 '02346255',
 '02346268',
 '02346269',
 '02346274',
 '02346285',
 '02346295',
 '02346297',
 '02346298',
 '02346300',
 '02346306',
 '02346308',
 '02346309',
 '02346310',
 '02346338',
 '02346345',
 '02346348',
 '02346350',
 '02346353',
 '02346368',
 '02346369',
 '02346388',
 '02346394',
 '02346395',
 '02346397',
 '02346398',
 '02346412',
 '02346413',
 '02346418']

In [ ]:
ana_dt_station = hydrobr.get_data.ANA.prec_data(code_station)

NameError: name 'hydrobr' is not defined

In [1]:
ana_dt_station.info()

NameError: name 'ana_dt_station' is not defined